### ISSUE TITLE
generar feature división

### ISSUE THREAD

**Issue by aelguetac** [G4-Diplomado-DevOps/Calculadora-Teams#4]
generar feature división

**Comment by aelguetac** [comment]
- [x] Validar QA

**Comment by ridexmoler** [comment]
Se valida el cambio y quedó funcionando según especificación,
Se valida
2 / 2 = 1
4 / 2 = 2
0 / 1 = 0
0 / 0 = Err: div by zero

**Comment by aelguetac** [comment]
se valida por QA
